version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports: 
      - "8091:8069"
    volumes:
      - ../../../config/multi_odoo_multi_db/odoo1:/etc/odoo
      - ../../../addons/multi_odoo_multi_db/odoo1:/mnt/extra-addons
      # - .:/etc/odoo
      # - ../../../addons/multi_odoo_multi_db/odoo1:/mnt/extra-addons