version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=nofeo
      - POSTGRES_PASSWORD=nofeo
  web:
    # build . mean build and get created image for this service use Dockerfile in it
    image: odoo:11.0
    depends_on:
      - db
    ports: 
      - "8090:8069"
    volumes:
      - ../../config/single_odoo:/etc/odoo
      - ../../addons/single_odoo:/mnt/extra-addons
    # update addons command
    command: ["-u", "go_inside"]

  