version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports: 
      - "8092:8069"
    volumes:
      - ../../../config/multi_odoo_multi_db/odoo2:/etc/odoo
      - ../../../addons/multi_odoo_multi_db/odoo2:/mnt/extra-addons
