version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  web:
    # build . mean build and get created image for this service use Dockerfile in it
    image: odoo:11.0
    depends_on:
      - db
    ports: 
      - "8090:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: ["-u", "go_inside"]
  