version: "3"
services:
  postgre_db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/docker-data/pgdata
    volumes:
      - odoo-11-db-data:/var/lib/postgresql/docker-data/pgdata
  odoo_11:
    # build . mean build and get created image for this service use Dockerfile in it
    image: my_odoo_11:v1
    depends_on:
      - postgre_db
    ports: 
      - "8090:8069"
    volumes:
      - odoo-11-data:/odoo/datadir/odoo_11
      - ./config:/odoo/config/ 
      - ./addons:/odoo/extra-addons
    environment:
      - HOST=postgre_db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  odoo-11-data:
  odoo-11-db-data: